version: "3.8"

services:
  n8n:
    image: n8nio/n8n
    container_name: n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=manosundar.com
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - WEBHOOK_URL=https://manosundar.com
      - GENERIC_TIMEZONE=Asia/Kolkata
    volumes:
      - n8n_data:/home/node/.n8n
    restart: always

  cloudflared:
    image: cloudflare/cloudflared
    container_name: cloudflared
    command: tunnel run n8n-tunnel
    volumes:
      - ~/.cloudflared:/etc/cloudflared
    depends_on:
      - n8n
    restart: always

volumes:
  n8n_data:
